name: spm

on:
  pull_request:
  schedule:
    # Run every day at 11pm (PST) - cron uses UTC times
    - cron:  '0 7 * * *'

jobs:
  swift-build-run:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Initialize xcodebuild
      run: xcodebuild -list
    - name: Verify iOS build
      run:  xcodebuild -sdk 'iphonesimulator' -destination 'platform=iOS Simulator,name=iPhone 11' -scheme GoogleAppMeasurement
    - name: Verify tvOS build
      run:  xcodebuild -sdk 'appletvsimulator' -destination 'platform=tvOS Simulator,name=Apple TV' -scheme GoogleAppMeasurement
    - name: Verify macOS build
      run:  xcodebuild -sdk 'macosx' -destination 'platform=macOS' -scheme GoogleAppMeasurement
